media:
  input: src/assets
  output: /assets

content:
  - name: blog
    label: Blog
    type: collection
    path: src/blog
    filename: "{primary}.md"
    view:
      fields: [ title, published, featured, date ]
    fields:
      - { label: "Published", name: "published", type: "boolean", default: false }
      - { label: "Title", name: "title", type: "string" }
      - { label: "Short Description", name: "description", type: "text" }
      - { label: "Featured Image", name: "image", type: "image" }
      - { label: "Image Caption", name: "imageAlt", type: "string" }
      - { label: "Date", name: "date", type: "date" }
      - { label: "Featured", name: "featured", type: "boolean", default: false }
      - name: tags
        label: Tag
        type: select
        options:
          creatable: true
          multiple: true
          values: [ Front-end Development, JavaScript, CSS, C#, Career, SEO, Accessibility ]
      - { label: "Body", name: "body", type: "rich-text" }
  - name: projects
    label: Projects
    type: collection
    path: src/projects
    filename: "{primary}.md"
    view: 
      fields: [title, featured, date]
    fields:
      - { label: "Project Name", name: "title", type: "string" }
      - { label: "Short Description", name: "description", type: "text" }
      - { label: "Project Image", name: "image", type: "image" }
      - { label: "Project Date", name: "date", type: "date" }
      - { label: "Featured", name: "featured", type: "boolean", default: false }
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [ JavaScript, Custom CSS, Webflow, WordPress, UX/UI, Responsive Design, SQL, Bootstrap, Tailwind ]
      - { label: "Project Link", name: "link", type: "string" }
  - name: skills
    label: Skills
    type: collection
    path: src/skills
    filename: "{primary}.md"
    view:
        fields: [title, order]
    fields:
      - { label: "Skill Name", name: "title", type: "string" }
      - { label: "Order", name: "order", type: "number" }
      - { label: "Skills", name: "skills", type: "string", list: true }
  - name: index_meta
    label: Home Page
    path: src/index.njk
    type: file
    format: "yaml-frontmatter"
    fields:
      - { label: layout, name: "layout", type: string, hidden: true, default: base.njk }
      - { label: "Page Title", name: "title", type: "string" }
      - { label: "Meta Description", name: "description", type: "text" }
      - { label: "Social Image", name: "image", type: "image" }
  - name: contact_meta
    label: Contact Page
    path: src/contact.njk
    type: file
    format: "yaml-frontmatter"
    fields:
      - { label: layout, name: "layout", type: string, hidden: true, default: base.njk }
      - { label: "Page Title", name: "title", type: "string" }
      - { label: "Meta Description", name: "description", type: "text" }
      - { label: "Social Image", name: "image", type: "image" }
  - name: blog_meta
    label: Blog Page
    path: src/blog.njk
    type: file
    format: "yaml-frontmatter"
    fields:
      - { label: layout, name: "layout", type: string, hidden: true, default: base.njk }
      - { label: "Page Title", name: "title", type: "string" }
      - { label: "Meta Description", name: "description", type: "text" }
      - { label: "Social Image", name: "image", type: "image" }
  - name: project_meta
    label: Project Page
    path: src/projects.njk
    type: file
    format: "yaml-frontmatter"
    fields:
      - { label: layout, name: "layout", type: string, hidden: true, default: base.njk }
      - { label: "Page Title", name: "title", type: "string" }
      - { label: "Meta Description", name: "description", type: "text" }
      - { label: "Social Image", name: "image", type: "image" }
  - name: "hero"
    label: Home - Hero
    path: src/_data/hero.json
    type: file
    fields:
      - { label: "Name", name: "name", type: "string" }
      - { label: "Greeting", name: "greeting", type: "string" }
      - { label: "Description", name: "description", type: "text" }
      - { label: "First CTA Text", name: "firstCtaText", type: "string" }
      - { label: "First CTA URL", name: "firstCtaUrl", type: "string" }
      - { label: "Second CTA Text", name: "secondCtaText", type: "string" }
      - { label: "Second CTA URL", name: "secondCtaUrl", type: "string" }
      - { label: "Image", name: "image", type: "image" }
  - name: about
    label: Home - About
    path: src/_data/about.json
    type: file
    fields:
      - { label: "Heading", name: "heading", type: "string" }
      - name: "description"
        label: "Description"
        type: "string"
        list: true      
      - { label: "Image", name: "image", type: "image" }
      - { label: "CTA Text", name: "ctaText", type: "string" }
      - { label: "CTA URL", name: "ctaUrl", type: "string" }
  - name: services
    label: Home - Services
    path: src/_data/services.json
    type: file
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Subtitle", name: "subtitle", type: "string" }
      - name: "cards"
        label: "Service Cards"
        type: "object"
        list: 
          collapsible:
            collapsed: true # Default collapsed state
            summary: "{Title} ({index})" # Template string using field values and {index}
        fields:
          - { label: "Icon (Lucide name)", name: "icon", type: "string" }
          - { label: "Title", name: "title", type: "string" }
          - { label: "Description", name: "description", type: "text" }

settings:
      content:
        merge: true